---
- name: Join Cluster
  command: "kubeadm join --token {{ token }} --discovery-token-unsafe-skip-ca-verification {{ master_ip }}:6443"
  ignore_errors: True
  register: join
- block:
    - command: "kubeadm reset"
    - command: "kubeadm join --token {{ token }} --discovery-token-unsafe-skip-ca-verification {{ master_ip }}:6443"
  when: join | failed
