---
# tasks file for kubeadm_nodes

- debug:
    msg: "{{ hostvars[groups['masters'][0]].ansible_default_ipv4.address }}"

- name: Join Cluster
  command: "kubeadm join --token {{ token }} {{ master_ip }}:6443"
