---
- include_role:
    name: ansible.kubernetes-modules
  when: wait_kubevirt_rollout

- file:
    path: "{{ manifests_path }}"
    recurse: True
    state: directory

- name: git clone kubevirt master
  git:
    repo: "{{ repo }}"
    dest: "{{ checkout_path }}"
  register: checkout
  delegate_to: localhost

- name: Find All Templates
  find:
    paths: "{{ manifests_path }}"
    pattern: "^((?!demo).)*$"
    use_regex: True
    recurse: True
  register: templates
  delegate_to: localhost

- name: Process Templates
  template:
    src: "{{ item.path }}"
    dest: "{{ item.path | splitext | first }}"
  with_items: "{{ templates.files }}"
  register: template_files

- command: "kubectl apply -f {{ item.dest | default(item.path) }} -n {{ namespace }}"
  when: item | changed
  with_items: "{{ template_files.results }}"

- name: Wait for KubeVirt DaemonSet rollout
  k8s_v1beta1_daemon_set:
    name: "{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ namespace }}"
  register: ds
  until: ds['daemon_set']['status']['number_available'] == ds['daemon_set']['status']['desired_number_scheduled']
  delay: "{{ until_delay }}"
  retries: "{{ until_retries }}"
  with_items:
    - virt-handler
    - libvirt
  when: wait_kubevirt_rollout

- name: Wait for KubeVirt deployment rollout
  k8s_extensions_v1beta1_deployment:
    name: "{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ namespace }}"
  register: deployment
  until: "'Available' in deployment['deployment']['status']['conditions'][0].type"
  delay: "{{ until_delay }}"
  retries: "{{ until_retries }}"
  with_items:
    - haproxy
    - spice-proxy
    - virt-api
    - virt-controller
  when: wait_kubevirt_rollout

- name: Expose haproxy
  command: "{{ item }}"
  with_items:
    - "oc expose deploy haproxy --port=8184"
    - "oc expose svc haproxy"
  when: install_openshift

