---
- include_role:
    name: ansible.kubernetes-modules
  when: wait_kubevirt_rollout

- file:
    path: "{{ manifests_path }}"
    recurse: True
    state: directory

- name: git clone kubevirt master
  git:
    repo: "{{ repo }}"
    dest: "{{ checkout_path }}"
  register: checkout
  delegate_to: localhost

- name: Find All Templates
  find:
    paths: "{{ manifests_path }}"
    pattern: "^((?!demo).)*$"
    use_regex: True
    recurse: True
  register: templates
  delegate_to: localhost

- name: Process Templates
  template:
    src: "{{ item.path }}"
    dest: "{{ item.path | splitext | first }}"
  with_items: "{{ templates.files }}"
  register: template_files

- name: OpenShift Prereq
  command: "{{ item }}"
  with_items:
    - "oc project kube-system"
    - "oc adm policy add-scc-to-user privileged -z kubevirt-infra"
    - "oc adm policy add-scc-to-user hostmount-anyuid -z kubevirt-infra"
  when: install_openshift

- command: "kubectl apply -f {{ item.dest | default(item.path) }} -n {{ namespace }}"
  when: item | changed
  with_items: "{{ template_files.results }}"

  #- name: Expose KubeVirt Services
  #  template:
  #    src: "external-services.yaml.j2"
  #    dest: "{{ manifests_path}}/external-{{ item.service_name }}.yaml"
  #  register: output_file
  #  vars:
  #    service_name: "{{ item.service_name }}"
  #    service_port: "{{ item.service_port }}"
  #  with_items: "{{ kubevirt_services }}"
  #  when: expose_externally

  #- command: "kubectl apply -f {{ item.dest | default(item.path) }}"
  #  ignore_errors: True
  #  when: (item | changed) and expose_externally
  #  with_items: "{{ output_file.results }}"

- name: Wait for KubeVirt DaemonSet rollout
  k8s_v1beta1_daemon_set:
    name: "{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ namespace }}"
  register: ds
  until: ds['daemon_set']['status']['number_available'] == ds['daemon_set']['status']['desired_number_scheduled']
  delay: "{{ until_delay }}"
  retries: "{{ until_retries }}"
  with_items:
    - virt-handler
    - libvirt
  when: wait_kubevirt_rollout

- name: Wait for KubeVirt deployment rollout
  k8s_extensions_v1beta1_deployment:
    name: "{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ namespace }}"
  register: deployment
  until: "'Available' in deployment['deployment']['status']['conditions'][0].type"
  delay: "{{ until_delay }}"
  retries: "{{ until_retries }}"
  with_items:
    - haproxy
    - spice-proxy
    - virt-api
    - virt-controller
  when: wait_kubevirt_rollout

- name: Expose haproxy
  command: "{{ item }}"
  with_items:
    - "oc expose deploy haproxy --port=8184"
    - "oc expose svc haproxy"
  when: install_openshift

