---
- name: Create Kubernetes virtual machines
  hosts: kube
  connection: local
  gather_facts: False
  any_errors_fatal: True
  serial: 1
  tasks:
    - include_role:
        name: local_vm
      when: create_local_vm

- name: Create iSCSI virtual machines
  hosts: iscsi
  connection: local
  gather_facts: False
  any_errors_fatal: True
  serial: 1
  tasks:
    - include_role:
        name: local_vm
      when: create_local_vm and install_iscsi

- name: Virtual Machine Configuration
  hosts: all
  gather_facts: True
  any_errors_fatal: True
  tasks:
    - include_role:
        name: networking
      when: configure_networking

- name: Kubernetes Prereq
  gather_facts: True
  hosts: kube
  any_errors_fatal: True
  tasks:
    - include_role:
        name: docker
      when: configure_docker
    - include_role:
        name: kubeadm_prereq
      when: install_kubeadm


- name: Configure kubernetes masters
  gather_facts: True
  any_errors_fatal: True
  hosts: masters
  tasks:
    - include_role:
        name: kubeadm_masters
      when: install_kubeadm

- name: Configure Kubernetes nodes
  gather_facts: True
  any_errors_fatal: True
  hosts: nodes
  tasks:
    - setup:
      delegate_to: "{{ groups['masters'][0] }}"
      delegate_facts: True

    - include_role:
        name: kubeadm_nodes
      when: install_kubeadm


- name: Configure KubeVirt
  gather_facts: True
  any_errors_fatal: True
  hosts: masters
  tasks:
    - include_role:
        name: kubevirt_prereq
      when: install_kubevirt

    - include_role:
        name: kubevirt
      when: install_kubevirt

- name: Configure iSCSI
  hosts: iscsi
  connection: local
  gather_facts: False
  any_errors_fatal: True
  serial: 1
  tasks:
    - include_role:
        name: iscsi
      when: install_iscsi
