---
- name: Create Kubernetes or OpenShift virtual machines
  hosts: kube
  connection: local
  gather_facts: False
  any_errors_fatal: True
  serial: 1
  tasks:
    - include_role:
        name: local_vm
      when: create_local_vm

- name: Create iSCSI virtual machines
  hosts: iscsi
  connection: local
  gather_facts: False
  any_errors_fatal: True
  serial: 1
  tasks:
    - include_role:
        name: local_vm
      when: create_local_vm and install_iscsi

- name: Virtual Machine Configuration
  hosts: all
  gather_facts: True
  any_errors_fatal: True
  tasks:
    - include_role:
        name: networking
      when: configure_networking

- name: OpenShift Prereq
  gather_facts: True
  hosts: OSEv3
  any_errors_fatal: True
  tasks:
    - include_role:
        name: docker
      when: configure_docker
    - include_role:
        name: openshift_prereq
      when: install_openshift

- name: OpenShift
  gather_facts: True
  hosts: masters
  any_errors_fatal: True
  tasks:
    - include_role:
        name: openshift
      when: install_openshift

- import_playbook: /tmp/openshift-ansible/playbooks/deploy_cluster.yml
  when: install_openshift

- name: Configure KubeVirt
  gather_facts: True
  any_errors_fatal: True
  hosts: masters
  tasks:
    - include_role:
        name: kubevirt_prereq
      when: install_kubevirt

    - include_role:
        name: kubevirt
      when: install_kubevirt

- name: Configure iSCSI
  hosts: iscsi
  connection: local
  gather_facts: False
  any_errors_fatal: True
  serial: 1
  tasks:
    - include_role:
        name: iscsi
      when: install_iscsi
