---
- name: Create VMs
  hosts: all
  connection: local
  gather_facts: False
  any_errors_fatal: True
  serial: 1
  tasks:
    - include_role:
        name: local_vm
      when: create_local_vm

- name: Virtual Machine Configuration
  hosts: all
  gather_facts: True
  any_errors_fatal: True
  tasks:
    - include_role:
        name: partition
      when: configure_partition
    - include_role:
        name: networking
      when: configure_networking

- name: Kubernetes Prereq
  gather_facts: True
  hosts: kube
  any_errors_fatal: True
  tasks:
    - include_role:
        name: docker
      when: configure_docker
    - include_role:
        name: kubeadm_prereq
      when: install_kubeadm

- name: OpenShift Prereq
  gather_facts: True
  hosts: OSEv3
  any_errors_fatal: True
  tasks:
    - include_role:
        name: docker
      when: configure_docker
    - include_role:
        name: openshift_prereq
      when: install_openshift

- name: Configure kubernetes masters
  gather_facts: True
  any_errors_fatal: True
  hosts: masters
  tasks:
    - include_role:
        name: kubeadm_masters
      when: install_kubeadm

- name: Configure Kubernetes nodes
  gather_facts: True
  any_errors_fatal: True
  hosts: nodes
  tasks:
    - setup:
      delegate_to: "{{ groups['masters'][0] }}"
      delegate_facts: True

    - include_role:
        name: kubeadm_nodes
      when: install_kubeadm

- name: OpenShift
  gather_facts: True
  hosts: masters
  any_errors_fatal: True
  tasks:
    - include_role:
        name: openshift
      when: install_openshift

- import_playbook: /tmp/openshift-ansible/playbooks/deploy_cluster.yml
  when: install_openshift

- name: Configure KubeVirt
  gather_facts: True
  any_errors_fatal: True
  hosts: masters
  tasks:
    - include_role:
        name: kubevirt_prereq
      when: install_kubevirt

    - include_role:
        name: kubevirt
      when: install_kubevirt
