---
- name: Create VMs
  hosts: all
  connection: local
  gather_facts: False
  any_errors_fatal: True
  serial: 1
  tasks:
    - include_role:
        name: local_vm
      when: create_local_vm

- name: Kubernetes and KubeVirt
  gather_facts: True
  hosts: all
  any_errors_fatal: True
  tasks:
    - include_role:
        name: partition
      when: configure_partition
    - include_role:
        name: docker
      when: configure_docker
    - include_role:
        name: networking
      when: configure_networking
    - include_role:
        name: kubeadm_prereq
      when: install_kubeadm

- name: Configure kubernetes masters
  gather_facts: True
  any_errors_fatal: True
  hosts: masters
  tasks:
    - include_role:
        name: kubeadm_masters
      when: install_kubeadm

- name: Configure Kubernetes nodes
  gather_facts: True
  any_errors_fatal: True
  hosts: nodes
  tasks:
    - setup:
      delegate_to: "{{ groups['masters'][0] }}"
      delegate_facts: True

    - include_role:
        name: kubeadm_nodes
      when: install_kubeadm


- name: Configure KubeVirt
  gather_facts: True
  any_errors_fatal: True
  hosts: masters
  tasks:
    - name: Install Packages to test deployment
      yum:
        pkg: "{{ item }}"
        state: latest
      with_items:
        - epel-release
      when: wait_kubevirt_rollout

      # TODO: this could be replaced by an ansible kube modules RPM need to find it.
    - name: Install pip
      yum:
        pkg: "{{ item }}"
        state: latest
      with_items:
        - python2-pip
      when: wait_kubevirt_rollout

    - name: Install Python pip packages to test deployment
      pip:
        name: "{{ item  }}"
        state: latest
      with_items:
        - pip
        - setuptools
        - openshift
      when: wait_kubevirt_rollout

    - include_role:
        name: kubevirt
