---
token: "{{ lookup('password', '/tmp/kube_token_first chars=ascii_letters,digits length=6') | lower }}.{{ lookup('password', '/tmp/kube_token_second chars=ascii_letters,digits length=16') | lower }}"

dns4: "192.168.122.1"
gateway: 192.168.122.1
mask: 24

domain_name: "example.com"
ansible_ssh_username: root
ansible_password: wileyfuse


configure_partition: False
configure_docker: True
configure_networking: True

# use kubeadm to install kubernetes
install_kubeadm: False
install_openshift: True
install_kubevirt: True
create_local_vm: True

wait_kubevirt_rollout: True


