---
token: "{{ lookup('password', '/tmp/kube_token_first chars=ascii_letters,digits length=6') | lower }}.{{ lookup('password', '/tmp/kube_token_second chars=ascii_letters,digits length=16') | lower }}"


dns4: "192.168.122.1"
gateway: 192.168.122.1
mask: 24
ansible_ssh_username: root
ansible_password:


configure_partition: False
configure_docker: False
configure_networking: False
install_kubeadm: False

wait_kubevirt_rollout: True


